[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Atur kecepatan serial monitor
monitor_speed = 115200

; Jika butuh optimasi memori saat upload BLE (terkadang BLE butuh partisi lebih besar)
board_build.partitions = huge_app.csv
